import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { copyFileSync, existsSync, readFileSync } from "fs";
import { resolve } from "path";

const banner = `(function(){ 
  if(typeof process!=="undefined" && process.release && process.release.name==="node"){
    try { Object.defineProperty(process,"release",{ value: Object.assign({},process.release,{name:"browser"}), writable:true, configurable:true }); } catch(_){}
  } 
})();
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const wasmFiles = [
  "ort-wasm-simd-threaded.wasm",
  "ort-wasm-simd-threaded.jsep.wasm",
  "ort-wasm-simd-threaded.jspi.wasm",
  "ort-wasm-simd-threaded.asyncify.wasm",
  "ort-wasm-simd-threaded.jsep.mjs",
];

const wasmCopyPlugin = {
  name: "copy-wasm",
  setup(build) {
    build.onEnd(() => {
      const srcDir = resolve("node_modules/onnxruntime-web/dist");
      const destDir = resolve(".");
      for (const f of wasmFiles) {
        const src = resolve(srcDir, f);
        const dest = resolve(destDir, f);
        if (existsSync(src)) {
          copyFileSync(src, dest);
        } else {
          console.warn(`WASM file not found: ${src}`);
        }
      }
    });
  },
};

const transformersWebPlugin = {
  name: "transformers-web",
  setup(build) {
    build.onResolve({ filter: /^@huggingface\/transformers$/ }, () => {
      return {
        path: resolve("node_modules/@huggingface/transformers/dist/transformers.web.js"),
      };
    });
    build.onLoad({ filter: /transformers\.web\.js$/ }, (args) => {
      const content = readFileSync(args.path, "utf-8");
      return {
        contents: content.replace(
          "if (ORT_SYMBOL in globalThis) {",
          "if (false) {"
        ),
        loader: "js",
      };
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "fs",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [wasmCopyPlugin, transformersWebPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
